name: "Art-Net LED UI Config"
slug: "ha_artnet_led_uiconfig"
description: "Write ha-artnet-led YAML from the UI Config panel"
version: "0.1.4"
url: "https://github.com/speedy3wk/ha-artnet-led-uiconfig"
arch:
  - aarch64
  - amd64
  - armv7
build_from:
  aarch64: ghcr.io/hassio-addons/base-python:3.11
  amd64: ghcr.io/hassio-addons/base-python:3.11
  armv7: ghcr.io/hassio-addons/base-python:3.11
init: false
startup: application
boot: auto
ingress: true
ingress_port: 8099
hassio_api: true
homeassistant_api: true
ports:
  8099/tcp: 8099
map:
  - config:rw
options:
  ha_url: "http://supervisor/core/api"
  ha_token: ""
  include_file: "ha_artnet_led_uiconfig.yaml"
  append_to_configuration: true
  reload_service: "homeassistant.reload_core_config"
schema:
  ha_url: str
  ha_token: str
  include_file: str
  append_to_configuration: bool
  reload_service: str
